PROJNAME=SLC_Free_Open_Source
DEVICE=CY8C24423B
BASEDEVICE=CY8C24000B
PROJPATH=C:/Work/SLC_Free/SL55AE~1/SLC_FR~1/SLC_FR~1
PSOCDIR=C:/PROGRA~1/Cypress/PSOCDE~2/5.3/Common/CY3E64~1
INCLUDE_PATH=C:/PROGRA~1/Cypress/PSOCDE~2/5.3/Common/CY3E64~1/tools/include/CY8C24~3
CSRCS= main.c
LIBCSRCS=
STDCSRCS=
ASMSRCS=
LIBASMSRCS= adcinc.asm adcincint.asm amux4_0.asm amux4_1.asm dac6_vgnd.asm dac9_ia.asm insamp.asm lcd.asm psocconfig.asm psocconfigtbl.asm pwm8_heater.asm pwm8_heaterint.asm pwm8_nb_out.asm pwm8_nb_outint.asm pwm8_vout.asm pwm8_voutint.asm sleeptimer.asm sleeptimerint.asm
STDASMSRCS=
OBJECT_SOURCES= main.c
FILLVALUE=0x30
LASTROM=0xfff
LASTRAM=0xff
CODECOMPRESSOR=-O -elim:UserModules
MORE_CFLAGS=
RELSTART=0x150
INC_PATH=
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_0 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_0 SYSTEM_SMALL_MEMORY_MODEL:_equ_1 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=on
CONFIG_NAMES=slc_free_28_pin_feb_16_2013 
