/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
// =============================================================================
// FILENAME: PSoCAPI.h
// 
// Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
// 
// NOTES:
// Do not modify this file. It is generated by PSoC Designer each time the
// generate application function is run. The values of the parameters in this
// file can be modified by changing the values of the global parameters in the
// device editor.
// 
// =============================================================================
 
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "ADCINC.h"
#include "AMUX4_0.h"
#include "AMUX4_1.h"
#include "DAC6_VGND.h"
#include "DAC9_Ia.h"
#include "INSAMP.h"
#include "LCD.h"
#include "PWM8_Heater.h"
#include "PWM8_NB_Out.h"
#include "PWM8_Vout.h"
#include "SleepTimer.h"

#endif
