/******************************************************************************
*  Generated by PSoC Designer 5.3.2710
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "ADCINC.h"
#include "AMUX4_0.h"
#include "AMUX4_1.h"
#include "DAC6_VGND.h"
#include "DAC9_Ia.h"
#include "INSAMP.h"
#include "LCD.h"
#include "PWM8_Heater.h"
#include "PWM8_NB_Out.h"
#include "PWM8_Vout.h"
#include "SleepTimer.h"

#endif
