;  Generated by PSoC Designer 5.3.2710
;
include "m8c.inc"
;  Personalization tables 
export LoadConfigTBL_slc_free_28_pin_feb_16_2013_Bank1
export LoadConfigTBL_slc_free_28_pin_feb_16_2013_Bank0
export LoadConfigTBL_slc_free_28_pin_feb_16_2013_Ordered
AREA lit(rom, rel)
LoadConfigTBL_slc_free_28_pin_feb_16_2013_Bank0:
;  Instance name ADCINC, User Module ADCINC
;       Instance name ADCINC, Block Name ADC(ASD11)
	db		84h, 90h		;ADCINC_AtoDcr0(ASD11CR0)
	db		85h, 00h		;ADCINC_AtoDcr1(ASD11CR1)
	db		86h, 60h		;ADCINC_AtoDcr2(ASD11CR2)
	db		87h, f8h		;ADCINC_AtoDcr3(ASD11CR3)
;       Instance name ADCINC, Block Name PWM(DBB00)
	db		23h, 00h		;ADCINC_PWMcr0(DBB00CR0)
	db		21h, 00h		;ADCINC_PWMdr1(DBB00DR1)
	db		22h, 01h		;ADCINC_PWMdr2(DBB00DR2)
;  Instance name AMUX4_0, User Module AMUX4
;  Instance name AMUX4_1, User Module AMUX4
;  Instance name DAC6_VGND, User Module DAC6
;       Instance name DAC6_VGND, Block Name DAC(ASC10)
	db		80h, 80h		;DAC6_VGND_CR0(ASC10CR0)
	db		81h, 40h		;DAC6_VGND_CR1(ASC10CR1)
	db		82h, a0h		;DAC6_VGND_CR2(ASC10CR2)
	db		83h, 30h		;DAC6_VGND_CR3(ASC10CR3)
;  Instance name DAC9_Ia, User Module DAC9
;       Instance name DAC9_Ia, Block Name LSB(ASD20)
	db		90h, 80h		;DAC9_Ia_LSB_CR0(ASD20CR0)
	db		91h, 80h		;DAC9_Ia_LSB_CR1(ASD20CR1)
	db		92h, 20h		;DAC9_Ia_LSB_CR2(ASD20CR2)
	db		93h, 30h		;DAC9_Ia_LSB_CR3(ASD20CR3)
;       Instance name DAC9_Ia, Block Name MSB(ASC21)
	db		94h, a0h		;DAC9_Ia_MSB_CR0(ASC21CR0)
	db		95h, 41h		;DAC9_Ia_MSB_CR1(ASC21CR1)
	db		96h, a0h		;DAC9_Ia_MSB_CR2(ASC21CR2)
	db		97h, 34h		;DAC9_Ia_MSB_CR3(ASC21CR3)
;  Instance name INSAMP, User Module INSAMP
;       Instance name INSAMP, Block Name INV(ACB00)
	db		71h, ddh		;INSAMP_INV_CR0(ACB00CR0)
	db		72h, 21h		;INSAMP_INV_CR1(ACB00CR1)
	db		73h, 20h		;INSAMP_INV_CR2(ACB00CR2)
	db		70h, 00h		;INSAMP_INV_CR3(ACB00CR3)
;       Instance name INSAMP, Block Name NON_INV(ACB01)
	db		75h, 1ch		;INSAMP_NON_INV_CR0(ACB01CR0)
	db		76h, 21h		;INSAMP_NON_INV_CR1(ACB01CR1)
	db		77h, 20h		;INSAMP_NON_INV_CR2(ACB01CR2)
	db		74h, 00h		;INSAMP_NON_INV_CR3(ACB01CR3)
;  Instance name LCD, User Module LCD
;  Instance name PWM8_Heater, User Module PWM8
;       Instance name PWM8_Heater, Block Name PWM8(DBB01)
	db		27h, 00h		;PWM8_Heater_CONTROL_REG(DBB01CR0)
	db		25h, ffh		;PWM8_Heater_PERIOD_REG(DBB01DR1)
	db		26h, 00h		;PWM8_Heater_COMPARE_REG(DBB01DR2)
;  Instance name PWM8_NB_Out, User Module PWM8
;       Instance name PWM8_NB_Out, Block Name PWM8(DCB03)
	db		2fh, 00h		;PWM8_NB_Out_CONTROL_REG(DCB03CR0)
	db		2dh, ffh		;PWM8_NB_Out_PERIOD_REG(DCB03DR1)
	db		2eh, 00h		;PWM8_NB_Out_COMPARE_REG(DCB03DR2)
;  Instance name PWM8_Vout, User Module PWM8
;       Instance name PWM8_Vout, Block Name PWM8(DCB02)
	db		2bh, 00h		;PWM8_Vout_CONTROL_REG(DCB02CR0)
	db		29h, ffh		;PWM8_Vout_PERIOD_REG(DCB02DR1)
	db		2ah, 00h		;PWM8_Vout_COMPARE_REG(DCB02DR2)
;  Instance name SleepTimer, User Module SleepTimer
;  Global Register values Bank 0
	db		60h, 09h		; AnalogColumnInputSelect register (AMX_IN)
	db		66h, 00h		; AnalogComparatorControl1 register (CMP_CR1)
	db		63h, 3fh		; AnalogReferenceControl register (ARF_CR)
	db		65h, 00h		; AnalogSyncControl register (ASY_CR)
	db		e6h, 02h		; DecimatorControl_0 register (DEC_CR0)
	db		e7h, 02h		; DecimatorControl_1 register (DEC_CR1)
	db		d6h, 00h		; I2CConfig register (I2CCFG)
	db		b0h, 00h		; Row_0_InputMux register (RDI0RI)
	db		b1h, 00h		; Row_0_InputSync register (RDI0SYN)
	db		b2h, 00h		; Row_0_LogicInputAMux register (RDI0IS)
	db		b3h, 33h		; Row_0_LogicSelect_0 register (RDI0LT0)
	db		b4h, 33h		; Row_0_LogicSelect_1 register (RDI0LT1)
	db		b5h, 88h		; Row_0_OutputDrive_0 register (RDI0SRO0)
	db		b6h, 08h		; Row_0_OutputDrive_1 register (RDI0SRO1)
	db		ffh
LoadConfigTBL_slc_free_28_pin_feb_16_2013_Bank1:
;  Instance name ADCINC, User Module ADCINC
;       Instance name ADCINC, Block Name ADC(ASD11)
;       Instance name ADCINC, Block Name PWM(DBB00)
	db		20h, 31h		;ADCINC_PWMfn(DBB00FN)
	db		21h, 16h		;ADCINC_PWMsl(DBB00IN)
	db		22h, 40h		;ADCINC_PWMos(DBB00OU)
;  Instance name AMUX4_0, User Module AMUX4
;  Instance name AMUX4_1, User Module AMUX4
;  Instance name DAC6_VGND, User Module DAC6
;       Instance name DAC6_VGND, Block Name DAC(ASC10)
;  Instance name DAC9_Ia, User Module DAC9
;       Instance name DAC9_Ia, Block Name LSB(ASD20)
;       Instance name DAC9_Ia, Block Name MSB(ASC21)
;  Instance name INSAMP, User Module INSAMP
;       Instance name INSAMP, Block Name INV(ACB00)
;       Instance name INSAMP, Block Name NON_INV(ACB01)
;  Instance name LCD, User Module LCD
;  Instance name PWM8_Heater, User Module PWM8
;       Instance name PWM8_Heater, Block Name PWM8(DBB01)
	db		24h, 31h		;PWM8_Heater_FUNC_REG(DBB01FN)
	db		25h, 11h		;PWM8_Heater_INPUT_REG(DBB01IN)
	db		26h, 44h		;PWM8_Heater_OUTPUT_REG(DBB01OU)
;  Instance name PWM8_NB_Out, User Module PWM8
;       Instance name PWM8_NB_Out, Block Name PWM8(DCB03)
	db		2ch, 31h		;PWM8_NB_Out_FUNC_REG(DCB03FN)
	db		2dh, 14h		;PWM8_NB_Out_INPUT_REG(DCB03IN)
	db		2eh, 06h		;PWM8_NB_Out_OUTPUT_REG(DCB03OU)
;  Instance name PWM8_Vout, User Module PWM8
;       Instance name PWM8_Vout, Block Name PWM8(DCB02)
	db		28h, 31h		;PWM8_Vout_FUNC_REG(DCB02FN)
	db		29h, 14h		;PWM8_Vout_INPUT_REG(DCB02IN)
	db		2ah, 05h		;PWM8_Vout_OUTPUT_REG(DCB02OU)
;  Instance name SleepTimer, User Module SleepTimer
;  Global Register values Bank 1
	db		61h, 00h		; AnalogClockSelect1 register (CLK_CR1)
	db		69h, 00h		; AnalogClockSelect2 register (CLK_CR2)
	db		60h, 05h		; AnalogColumnClockSelect register (CLK_CR0)
	db		62h, 29h		; AnalogIOControl_0 register (ABF_CR0)
	db		67h, 33h		; AnalogLUTControl0 register (ALT_CR0)
	db		68h, 00h		; AnalogLUTControl1 register (ALT_CR1)
	db		63h, 00h		; AnalogModulatorControl_0 register (AMD_CR0)
	db		66h, 00h		; AnalogModulatorControl_1 register (AMD_CR1)
	db		d1h, 00h		; GlobalDigitalInterconnect_Drive_Even_Input register (GDI_E_IN)
	db		d3h, 00h		; GlobalDigitalInterconnect_Drive_Even_Output register (GDI_E_OU)
	db		d0h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Input register (GDI_O_IN)
	db		d2h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Output register (GDI_O_OU)
	db		e1h, 0bh		; OscillatorControl_1 register (OSC_CR1)
	db		e2h, 00h		; OscillatorControl_2 register (OSC_CR2)
	db		dfh, 2fh		; OscillatorControl_3 register (OSC_CR3)
	db		deh, 00h		; OscillatorControl_4 register (OSC_CR4)
	db		ddh, 00h		; OscillatorGlobalBusEnableControl register (OSC_GO_EN)
	db		ffh
AREA psoc_config(rom, rel)
LoadConfigTBL_slc_free_28_pin_feb_16_2013_Ordered:
;  Ordered Global Register values
	M8C_SetBank0
	mov	reg[00h], 00h		; Port_0_Data register (PRT0DR)
	M8C_SetBank1
	mov	reg[00h], 04h		; Port_0_DriveMode_0 register (PRT0DM0)
	mov	reg[01h], fbh		; Port_0_DriveMode_1 register (PRT0DM1)
	M8C_SetBank0
	mov	reg[03h], fbh		; Port_0_DriveMode_2 register (PRT0DM2)
	mov	reg[02h], 00h		; Port_0_GlobalSelect register (PRT0GS)
	M8C_SetBank1
	mov	reg[02h], 00h		; Port_0_IntCtrl_0 register (PRT0IC0)
	mov	reg[03h], 00h		; Port_0_IntCtrl_1 register (PRT0IC1)
	M8C_SetBank0
	mov	reg[01h], 00h		; Port_0_IntEn register (PRT0IE)
	mov	reg[04h], 00h		; Port_1_Data register (PRT1DR)
	M8C_SetBank1
	mov	reg[04h], 70h		; Port_1_DriveMode_0 register (PRT1DM0)
	mov	reg[05h], 8fh		; Port_1_DriveMode_1 register (PRT1DM1)
	M8C_SetBank0
	mov	reg[07h], 8fh		; Port_1_DriveMode_2 register (PRT1DM2)
	mov	reg[06h], 70h		; Port_1_GlobalSelect register (PRT1GS)
	M8C_SetBank1
	mov	reg[06h], 00h		; Port_1_IntCtrl_0 register (PRT1IC0)
	mov	reg[07h], 00h		; Port_1_IntCtrl_1 register (PRT1IC1)
	M8C_SetBank0
	mov	reg[05h], 00h		; Port_1_IntEn register (PRT1IE)
	mov	reg[08h], 00h		; Port_2_Data register (PRT2DR)
	M8C_SetBank1
	mov	reg[08h], ffh		; Port_2_DriveMode_0 register (PRT2DM0)
	mov	reg[09h], 00h		; Port_2_DriveMode_1 register (PRT2DM1)
	M8C_SetBank0
	mov	reg[0bh], 00h		; Port_2_DriveMode_2 register (PRT2DM2)
	mov	reg[0ah], 00h		; Port_2_GlobalSelect register (PRT2GS)
	M8C_SetBank1
	mov	reg[0ah], 00h		; Port_2_IntCtrl_0 register (PRT2IC0)
	mov	reg[0bh], 00h		; Port_2_IntCtrl_1 register (PRT2IC1)
	M8C_SetBank0
	mov	reg[09h], 00h		; Port_2_IntEn register (PRT2IE)
	M8C_SetBank0
	ret


; PSoC Configuration file trailer PsocConfig.asm
